steps:  
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: mvn
    args: ['--version']
    
  - name: maven:3.6.0-jdk-11-slim
    dir: microservices-app-one/
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true']